#!/usr/bin/env python3
"""Builds ~/.config/zsh/p10k.zsh from Powerlevel10k's own "lean" template.

Starting from the upstream template (rather than a hand-written file) keeps every segment's
defaults correct; this script only changes what makes it the Summit prompt:
  - which segments are shown, in the Summit colours
  - transient prompt on (old prompts collapse to a single arrow, so scrollback stays clean)
  - instant prompt quiet (the prompt appears at once while the rest of zsh loads)
Re-run it after updating Powerlevel10k:  python3 shell/make-p10k.py (summit-desktop)
"""
import os, re, sys

HOME = os.path.expanduser("~")
SRC = f"{HOME}/.local/share/zsh/plugins/powerlevel10k/config/p10k-lean.zsh"
OUT = f"{HOME}/.config/zsh/p10k.zsh"

TEAL, TEAL_B, BLUE, PURPLE = "#4fd1c5", "#81e6d9", "#7cb7ff", "#b9a3f5"
GREEN, AMBER, RED = "#84cc6a", "#e3b341", "#f47067"
TEXT, MUTED, DIM = "#dce3ea", "#8693a1", "#5c6773"

s = open(SRC).read()
changes = []

def sub(pattern, repl, count=1, flags=re.M):
    global s
    new, n = re.subn(pattern, repl, s, count=count, flags=flags)
    if n == 0:
        sys.exit(f"make-p10k: the template changed, pattern not found: {pattern}")
    s = new
    changes.append(pattern)

def setvar(name, value):
    """Set `typeset -g POWERLEVEL9K_<name>=...` (first occurrence), quoting the value."""
    sub(rf"^(\s*typeset -g POWERLEVEL9K_{name}=).*$", lambda m: m.group(1) + value)

# ---- segments -----------------------------------------------------------------------------
sub(r"typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=\(.*?\n  \)",
    """typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command (only when it failed)
    command_execution_time  # how long the last command took (only when it was slow)
    background_jobs         # presence of background jobs
    virtualenv              # python virtual environment
    node_version            # node.js version (only inside a node project)
    go_version              # go version (only inside a go project)
    context                 # user@host (only over ssh or as root)
    # =========================[ Line #2 ]=========================
    newline
  )""", flags=re.S)

setvar("MODE", "nerdfont-v3")

# ---- colours ------------------------------------------------------------------------------
setvar(r"PROMPT_CHAR_OK_\{VIINS,VICMD,VIVIS,VIOWR\}_FOREGROUND", f"'{TEAL}'")
setvar(r"PROMPT_CHAR_ERROR_\{VIINS,VICMD,VIVIS,VIOWR\}_FOREGROUND", f"'{RED}'")
setvar("DIR_FOREGROUND", f"'{TEAL}'")
setvar("DIR_SHORTENED_FOREGROUND", f"'{MUTED}'")
setvar("DIR_ANCHOR_FOREGROUND", f"'{TEAL_B}'")
setvar("STATUS_ERROR_FOREGROUND", f"'{RED}'")
setvar("COMMAND_EXECUTION_TIME_FOREGROUND", f"'{MUTED}'")
setvar("COMMAND_EXECUTION_TIME_THRESHOLD", "2")
setvar("BACKGROUND_JOBS_FOREGROUND", f"'{GREEN}'")
setvar("CONTEXT_FOREGROUND", f"'{AMBER}'")
setvar("VIRTUALENV_FOREGROUND", f"'{AMBER}'")
setvar("NODE_VERSION_FOREGROUND", f"'{GREEN}'")
setvar("GO_VERSION_FOREGROUND", f"'{BLUE}'")
setvar("TIME_FOREGROUND", f"'{DIM}'")

# git: branch in purple, changes in amber, untracked in blue, conflicts in red
sub(r"local       meta='%f'     # default foreground", f"local       meta='%F{{{MUTED}}}'  # muted")
sub(r"local      clean='%76F'   # green foreground", f"local      clean='%F{{{PURPLE}}}'  # purple")
sub(r"local   modified='%178F'  # yellow foreground", f"local   modified='%F{{{AMBER}}}'  # amber")
sub(r"local  untracked='%39F'   # blue foreground", f"local  untracked='%F{{{BLUE}}}'  # blue")
sub(r"local conflicted='%196F'  # red foreground", f"local conflicted='%F{{{RED}}}'  # red")
# the greys used while git status is still loading
sub(r"='%244F'  # grey foreground", f"='%F{{{DIM}}}'  # dim", count=0)

# ---- behaviour ----------------------------------------------------------------------------
setvar("TRANSIENT_PROMPT", "always")
setvar("INSTANT_PROMPT", "quiet")

header = f"""# Summit prompt for Powerlevel10k. GENERATED by shell/make-p10k.py (summit-desktop) from
# Powerlevel10k's "lean" template; edit that script, or change values here and accept that a
# regeneration overwrites them. Reference: https://github.com/romkatv/powerlevel10k#configuration
#
"""
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write(header + s)
print(f"wrote {OUT} ({len(changes)} changes applied)")
